qcom: qpnp-pq: Fix -Wpointer-to-int-cast
drivers/power/supply/qcom/qpnp-qg.c:4977:21: error: cast to smaller integer type 'u8' (aka 'unsigned char') from 'const void *' [-Werror,-Wvoid-pointer-to-int-cast]
        chip->qg_version = (u8)of_device_get_match_data(&pdev->dev);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix `chip->qg_version = (u8)of_device_get_match_data(&pdev->dev)`
by casting pointer value to enum qg_version instead of truncated
int type.

Bug: 171827315
Signed-off-by: YFMARCO <qahralandrwyd5@google.com>
Change-Id: I1dd1eb91bda9b44ca640a2c89c94d158abff5e7f